version: '3.8'

services:
  passengers-ingestion:
    build: ./passengers-ingestion
    container_name: passengers-ingestion
    env_file:
      - ../.env  # Usa el archivo .env centralizado en la raíz del proyecto
    environment:
      - PASSENGERS_API_URL=${PASSENGERS_API_URL}
      - S3_BUCKET=${S3_BUCKET}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - ~/.aws:/root/.aws:ro  # Monta credenciales de AWS en modo solo lectura
    networks:
      - ingestion-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  trips-ingestion:
    build: ./trips-ingestion
    container_name: trips-ingestion
    env_file:
      - ../.env  # Usa el archivo .env centralizado en la raíz del proyecto
    environment:
      - TRIPS_API_URL=${TRIPS_API_URL}
      - S3_BUCKET=${S3_BUCKET}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - ~/.aws:/root/.aws:ro  # Monta credenciales de AWS en modo solo lectura
    networks:
      - ingestion-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  tickets-ingestion:
    build: ./tickets-ingestion
    container_name: tickets-ingestion
    env_file:
      - ../.env  # Usa el archivo .env centralizado en la raíz del proyecto
    environment:
      - TICKETS_API_URL=${TICKETS_API_URL}
      - S3_BUCKET=${S3_BUCKET}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - ~/.aws:/root/.aws:ro  # Monta credenciales de AWS en modo solo lectura
    networks:
      - ingestion-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  ingestion-network:
    driver: bridge
